# Google Cloud Build configuration for Vtrpg
# This configuration builds the Docker image and pushes it to Artifact Registry
# 
# Prerequisites:
# - Enable Cloud Build API in your GCP project
# - Enable Artifact Registry API (or Container Registry API)
# - Create an Artifact Registry repository (recommended) or use Container Registry
# 
# To manually trigger a build:
#   gcloud builds submit --config=cloudbuild.yaml .
#
# To set up automatic builds from GitHub:
#   Connect your repository via Cloud Build Triggers in the GCP Console

steps:
  # Build the Docker image using the existing Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '.'
    timeout: '1200s'

  # Push the image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-sha'
    args:
      - 'push'
      - '${_IMAGE_NAME}:$COMMIT_SHA'

  # Push the image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-latest'
    args:
      - 'push'
      - '${_IMAGE_NAME}:latest'

  # Optional: Deploy to Cloud Run
  # Uncomment the following step to automatically deploy to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: 'deploy-cloud-run'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - '${_SERVICE_NAME}'
  #     - '--image=${_IMAGE_NAME}:$COMMIT_SHA'
  #     - '--region=${_REGION}'
  #     - '--platform=managed'
  #     - '--allow-unauthenticated'
  #     - '--port=8080'
  #     - '--set-env-vars=ALLOWED_ORIGINS=*,MAX_UPLOAD_SIZE=10485760,FRONTEND_DIR=/app/dist,UPLOAD_DIR=/data/uploads'
  #     - '--memory=512Mi'
  #     - '--cpu=1'
  #     - '--min-instances=0'
  #     - '--max-instances=10'

# Substitution variables
# Override these when running gcloud builds submit with --substitutions
substitutions:
  # Default to Artifact Registry format
  # Change PROJECT_ID to your actual GCP project ID
  _IMAGE_NAME: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/vtrpg'
  _REGION: 'us-central1'
  _REPOSITORY: 'vtrpg-repo'
  _SERVICE_NAME: 'vtrpg'

# Build options
options:
  # Use a machine with more resources for faster builds
  machineType: 'N1_HIGHCPU_8'
  # Increase disk size if needed for large builds
  diskSizeGb: 100
  # Enable Docker layer caching for faster subsequent builds
  # Note: This requires Cloud Build API v2
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

# Build timeout (20 minutes)
timeout: '1200s'

# Images to be pushed to the registry
# This makes them available in the Cloud Build UI
images:
  - '${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_IMAGE_NAME}:latest'

# Tags for organizing builds
tags:
  - 'vtrpg'
  - 'golang'
  - 'react'
  - 'websocket'
